name: SakuraTools
version: '${project.version}'
main: org.baijiu.sakuratools.SakuraTools
authors: [SakuraBaiJiu]
description: 专门为一些小的开发做的工具


commands:
  itemid:
    description: getItemID
  gm:
    description: changeGameMode
  fix:
    description: fixItem